---
- name: List available PowerVC Networks
  hosts: localhost
  tasks:
    - name: Retrieve list of all networks
      os_networks_info:
      register: result

    - name: Print Network list
      debug:
        msg: "{{ result | json_query(query) }}"
      vars:
        query: 'openstack_networks[*].
              {name: name, segment: "provider:segmentation_id", type: "provider:network_type", status: status}'
