---
# tasks file for roles/resolv_conf

- name: Load OS specific variables
  include_vars: "{{ ansible_system }}.yml"
  #when: ansible_system == "AIX"
  tags: resolv_conf

#- name: Load Linux specific variables
#  include_vars: Linux.yml
#  when: ansible_system == "Linux"
#  tags: resolv_conf


- name: Save existing resolv.conf file localy
  fetch:
    src:  "{{ DNS_File }}"
    dest: "{{ Target_Dir }}"
  tags: resolv_conf


- name: Copy New resolv.conf file onto target
  copy:
    src:  "{{ role_path }}/{{ DNS_Copy }}"
    dest: "{{ DNS_File }}"
    owner: root
    group: "{{ DNS_Group_Name }}"
    mode: '0644'
    backup: yes
  tags: resolv_conf

