---
- name: Build a new VM via Tower and PowerVC/OpenStack with 2 network interfaces
# This playbook will prompt for VM name, image,flavor
# Version 2 - prompt for IP addresses
# Version 3 - syntax
# Version 4 - quit playbooks if hostname is incorrect
# Version 5 - Tower
  hosts: localhost

  vars_prompt:
    - name: "VM_Name"
      prompt: "Enter name of new VM to create"
      private: no
      confirm: no
      name: "VM_Net_Name_1"
      prompt: "Enter name of primary network"
      private: no
      confirm: no
      name: "VM_Net_Name_2"
      prompt: "Enter name of secondary network"
      private: no
      confirm: no
      name: "VM_Net_IP_1"
      prompt: "Enter IP for primary interface"
      private: no
      confirm: no
      name: "VM_Net_IP_2"
      prompt: "Enter IP for secondary interface"
      private: no
      confirm: no
      name: "VM_Image_Name"
      prompt: "Enter name of image to use"
      private: no
      confirm: no
      name: "VM_Flavor_Name"
      prompt: "Enter name of compute template to use"
      private: no
      confirm: no


  tasks:
  - name: Display VM Name
    debug:
      msg: "Creating VM {{ VM_Name }}"

  - name: List Available Networks
    import_role:
      name: VM_network_list

  - name: Create network interfaces for VM
    import_role:
      name: VM_network_create

  - name: Pick VM images
    import_role:
      name: VM_image_pick

  - name: Pick VM flavors
    import_role:
      name: VM_flavor_pick

  - name: List existing VMs
    import_role:
      name: VM_name_list

  - name: Show details before creating VM
    pause:
      prompt: "\nCreate New VM  : '{{ VM_Name }}' \n       Networks : '{{VM_Net_Name_1 }}' & '{{VM_Net_Name_2}}'\n       Image   : {{ VM_Image_Name }} '{{ VM_Image_ID }}'\n       Flavour : {{ VM_Flavor_Name }} - vCPUs:{{ VM_Flavor_CPU }} Mem:{{ VM_Flavor_Mem }} '{{ VM_Flavor_ID }}'\n\nCreate VM with above details ? ( Y/N ) "
    register: VM_Create_prompt
    when: VM_Flavor_ID is defined
    tags: VM_Create

#  - name: Create new VM
#    import_role:
#      name: VM_create_vm
#    when:
#      - VM_Flavor_ID is defined
#      - VM_Create_prompt.user_input == "y" or VM_Create_prompt.user_input == "Y"
#    tags: VM_Create
