---
- name: List all VMs
  hosts: localhost
  tasks:
    - name: Retrieve list of all VMs 
      os_server_info:
#        properties:
#          "OS-EXT-STS:vm_state": inactive  # remove this line to list all images
      register: result

    - name: Print VM list
      debug:
        msg: "{{ result | json_query(query) }}"
      vars:
        query: 'openstack_servers[*].
              {name: name, IP: public_v4, State: "OS-EXT-STS:vm_state", Host: "OS-EXT-SRV-ATTR:hypervisor_hostname"}'
