---
- name: Run AIX configuration manager
# This playbook will prompt for VM name, number of disks and size of disk
  gather_facts: yes
  hosts: Lab-NIM-26

  tasks:
  - name: Show VM name
    debug:
      msg: "Running configuration manager on VM {{ VM_Name}}"
#
#  - name: Run configuration manager
#    include_role:
#      name: run_aix_cfgmgr
