---
# tasks file for DISK_create
- name: Set Disk Size Variables
  set_fact:
    DISK_Size: "{{ Size_of_disks }}"

- name: Set Disk Name
  set_fact:
    DISK_Name: "{{ VM_Name }}-disk-{{ disk_number }}"

- name: Create a new disk
  os_volume:
    state: present
    display_name: "{{ DISK_Name }}"
    size: "{{ DISK_Size }}"
    volume_type: "{{ Storage_Template }}"

- name: Increment count
  set_fact: count={{ count | int + 1}}
