---
# tasks file for VM_image_pick
# As this is for an older version of Ansible, we refer to ansible_facts below. Remove for newer versions.
- name: Get data for selected image
  set_fact:
    VM_Image_Array:  "{{ result.ansible_facts | json_query(query) }}"
  vars:
    query: "openstack_image[?name=='{{ VM_Image_Name }}' ]"

- name: Debug - Output Image Array
  debug:
    var: VM_Image_Array.0
    verbosity: 1

- name: Get data for selected image
  set_fact:
    VM_Image_ID: "{{ VM_Image_Array.0['id'] }}"
  when: VM_Image_Array.0 is defined

- name: Output ID for selected image
  debug:
    msg: "{{ VM_Image_Name }} - id:'{{ VM_Image_ID }}'"
  when: VM_Image_Array.0 is defined
