---
# tasks file for VM_image_list

- name: Retrieve list of all OS Distributions
  os_image_info:
  register: result

- name: Filter OS Distribution list
  set_fact:
    OS_Images: "{{ result | json_query('openstack_image[*].
          {os_distro: os_distro}') | unique }}"

- name: Debug - Output OS Distribution list
  debug:
    var: OS_Images
    verbosity: 1

- name: Display OS Distribution list
  set_fact:
    OS_list: "{{ OS_Image_Seq }} {{ item.os_distro }} )"
  with_items: "{{ OS_Heading }},{{ OS_Images }}"
  loop_control:
    index_var: OS_Image_Seq
    label: "{{ item.os_distro|center(width=8) }} "
  register: OS_Array

## Select OS_Distro from list
- name: Request OS Distro
  pause:
    prompt: "Enter name of os_distro to use (leave blank for ALL) "
  register: VM_OS_Input
  when:  VM_OS_Distro is undefined

- name: Set OS name
  set_fact:
    VM_OS_Distro: "{{ VM_OS_Input.user_input }}"
  when:  VM_OS_Distro is undefined

- name: Output OS List
  debug:
    msg: "Selected OS Distro = '{{ VM_OS_Distro }}'"

- name: Set OS Distro search for ALL parameters
  set_fact:
    ImageQuery: "openstack_image[*].{name: name, id: id, os_distro: os_distro, status: status, project: location.project.name}"
  when:  VM_OS_Distro == ""

- name: Set OS Distro search parameters
  set_fact:
    ImageQuery: "openstack_image[?properties.os_distro=='{{ VM_OS_Distro }}'].{name: name, id: id, os_distro: os_distro, status: status, project: location.project.name}"
  when:  VM_OS_Distro != ""

## List Images 
- name: Filter image list
  set_fact:
    VM_Images: "{{ result | json_query(ImageQuery) }}"

- name: Debug - Output Image list
  debug:
    var: VM_Images
    verbosity: 1

- name: Display list of images
  set_fact:
    image_list: "{{ VM_Image_Seq }} {{ item.name }} | os_distro: {{ item.os_distro }} | Status: {{ item.status }} | Project: {{ item.project }}  ( {{ item.id }} )"
  with_items: "{{ VM_Heading }},{{ VM_Images }}"
  loop_control:
    index_var: VM_Image_Seq
    label: "{{ item.name|center(width=45) }}|{{ item.os_distro|center(width=8) }} | {{ item.id|center(width=30) }} "
  register: VM_Array
