---
# tasks file for DISK_attach
- name: Set Disk Name
  set_fact:
    DISK_Name: "{{ VM_Name }}-disk-{{ UID }}-{{ disk_number }}"

- name: Attach New Disk
  os_server_volume:
    state: present
    server: "{{ VM_Name }}"
    volume: "{{ DISK_Name }}"

- name: Increment count
  set_fact: count={{ count | int + 1}}
