---
# tasks file for VM_flavor_list

- name: Retrieve list of all public flavors
  os_flavor_info:
  register: result
  tags: always

#- name: Debug - Output Flavors
#  debug:
#    var: result
#    #verbosity: 1
#  tags: never, Debug

- name: Filter flavor list
  set_fact:
    VM_Flavors: "{{ result | json_query('openstack_flavors[?is_public==`true`].
              {name: name, id: id, ram: ram, vcpus: vcpus}') }}"

- name: Debug - Output Flavors
  debug:
    var: VM_Flavors
    verbosity: 1

- name: Output List
  set_fact:
    flavor_list: "{{ item.name }} [ vCPUs: {{ item.vcpus }} , Mem: {{ item.ram }} , id: {{ item.id }} ]"
  with_items: "{{VM_Heading}},{{ VM_Flavors }}"
  loop_control:
    index_var: VM_Seq
    #label: "  Flavor = {{ item.name }}  [ vCPUs: {{ item.vcpus }} | Mem: {{ item.ram }} | id: {{ item.id }} ]  "
    #label: "{% if VM_Seq == 0 %}Seq{% else %}{{ VM_Seq|center(width=3) }}{% endif %} | {{ item.name|center(width=15) }}|{{ item.vcpus|center(width=9) }} | {{ item.ram|center(width=7) }} | {{ item.id }} "
    label: "{{ item.name|center(width=15) }}|{{ item.vcpus|center(width=9) }} | {{ item.ram|center(width=7) }} | {{ item.id }} "
  register: VM_Array

