- name: Retrieve list of all AIX images
  os_image_info:
    properties:
      os_distro: aix  # remove this line to list all images
  register: result

- name: Filter image list
  set_fact:
    images: "{{ result | json_query('openstack_image[*].
          {name: name, id: id, os_distro: os_distro, status: status,
          project: location.project.name}') }}"

- name: Debug - Output Image list
  debug:
    var: images
    verbosity: 1

- name: Display list of images
  set_fact:
    image_list: "{{ VM_Image_Seq }} {{ item.name }} | os_distro: {{ item.os_distro }} | Status: {{ item.status }} | Project: {{ item.project }}  ( {{ item.id }} )"
  with_items: "{{ images }}"
  loop_control:
    index_var: VM_Image_Seq
    label: "{{ VM_Image_Seq }}  AIX Image = '{{ item.name }}'  [ {{ item.id }} ]  "

- name: Request Image
  pause:
    prompt: "Enter name of image to use "
  register: VM_Image_Input
  when:  VM_Image_Name is undefined

- name: Set Image name
  set_fact:
    VM_Image_Name: "{{ VM_Image_Input.user_input }}"
  when:  VM_Image_Name is undefined

- name: Output Image List
  debug:
    var: VM_Image_Name

- name: Get data for selected image
  set_fact:
    VM_Image_Array:  "{{ result | json_query(query) }}"
  vars:
    query: "openstack_image[?name=='{{ VM_Image_Name }}' ]"

- name: Debug - Output Image Array
  debug:
    var: VM_Image_Array.0
    verbosity: 1

- name: Get data for selected image
  set_fact:
    VM_Image_ID: "{{ VM_Image_Array.0['id'] }}"

- name: Output ID for selected image
  debug:
    msg: "{{ VM_Image_Name }} - id:'{{ VM_Image_ID }}'"


